### ISSUE TITLE
Add Docker Image

### ISSUE THREAD

**Issue by ahahn94** [bpepple/bamf#26]
## Expected Behavior
Make Bamf runnable via Docker.

## Current Behavior
N/A

## Possible Solution
You can find the docker version of tenma here: https://github.com/Tenma-Server/Docker
As Bamf is a fork of tenma, some minor changes to the `Docker` file and the files in the `tenma` directory should be sufficient to get a working docker image.

**Comment by bpepple** [comment]
I looked at it in the past, and bamf has deviated enough from tenma that it would need quite a bit of surgery to work (Adding support for Huey, Gunicorn, etc.). If I get some free time I might work on this, but it's a fairly low priority. That being said... if someone wants to work on this that would be great.

**Comment by bpepple** [comment]
Spent a half-hour or so at lunch and worked on this. I've started a new git repo for this work at https://github.com/bpepple/bamf-docker for anyone that wants to follow this. I've set it up into five containers:

1. web/Django container
2. nginx container
3. Postgres container
4. Redis container
5. data container

![screenshot from 2018-05-25 14-21-49](https://user-images.githubusercontent.com/8381/40560430-fd2235ca-6027-11e8-950c-b5606034ab17.png)

**Note:** I've still need to update the bamf module for the project setting changes since I've done it locally only for testing, so you won't be able to test it yet.

**TODO Items**
* Still need to set-up a supervisord to run huey (hence no comics can be imported yet).
* Handle static project file (like the admin pages css, etc)
* Write some basic instructions.
* And I'm sure there are other items I'm forgetting, but for now it's a starting point.

**Comment by bpepple** [comment]
Going to hold off on working on this until [supervisor](https://github.com/Supervisor/supervisor) runs on Python3, since it will prevent a lot of the headaches (like having to virtualenv the django app & huey instance).

**Comment by bpepple** [comment]
Closing issue, since this project is no longer maintained (since I'm concentration on Thwip), and being archived.
