### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by trumblejoe** [bpepple/bamf#29]
Does BAMF currently have Windows support? I've seen some mention of gunicorn which is unix only, but could that be substituted for something like waitress?

**Comment by bpepple** [comment]
You should be able to run waitress in lieu of gunicorn. Theoretically you should also be able to run Bamf on a windows machine since Django can run on windows. It's entirely possible tho, there might be some bugs that would need to be squashed since I haven't had a Windows machine since the 90's, and don't really really give it much thought when I write code.

**Comment by trumblejoe** [comment]
I have it working on Windows, it seems to be working really well. The install was a bit of a pain finding a Windows Redis binary (https://github.com/tporadowski/redis), but other then that, following the linux steps through the windows program GUI's was simple enough.

Two major points I took away from the install, both of which that were not in the instructions: 

The installation instructions fail to mention that running 'python manage.py runserver' w/o specifying an IP address will default to local-host (which makes total sense in retrospect).

And after specifying an IP Address such as, for example, 192.168.1.101, the other issue is that in settings.py, under ALLOWED_HOSTS, it is necessary to fill in the empty brackets ['localhost', '127.0.0.1', '192.168.1.xxx'] so that the host header will match one of those entered values.

Closing this issue.
